### ISSUE TITLE
Progress WIT for all Ramsar wetlands

### ISSUE THREAD

**Issue by Bartesto** [Bartesto/wetlands#9]
Awaiting:

1. Names of all wetlands

2. New vectors for all to include appropriate veg to drive appropriate outputs from WIT

Will QA vectors then submit to GA - remember to check they are valid by GA standards

**Comment by ecostash** [comment]
Hi Bart,
   Hopefully I am doing this correctly. Attached should be a zip file containing:
i)   QGis file
ii)  All the shapefiles

I also sent ya an email.

Thanks.

Mike

[WIT_6AUG20.zip](https://github.com/Bartesto/wetlands/files/5049183/WIT_6AUG20.zip)

**Comment by ecostash** [comment]
Updated zip file with redundant shape files removed.
[WIT_6AUG20.zip](https://github.com/Bartesto/wetlands/files/5049775/WIT_6AUG20.zip)

**Comment by Bartesto** [comment]
Thanks Mike,

I'll amalgamate and show you what I will end up sending to GA.

Area calcs are done by:

- create an attribute field

- then populate it with an area calculation (right click in Arc...would be something similar in QGIS)

- helps to have shape file in projected not geodetic

**Comment by Bartesto** [comment]
New Ramsar wetlands of south west was submitted today for processing.

**Comment by Bartesto** [comment]
Mike

New WIT results are delivered.

Cheers
[WAresults19082020.zip](https://github.com/Bartesto/wetlands/files/5100001/WAresults19082020.zip)
